#!/usr/bin/env python3
"""
UserPromptSubmit hook — tracks cumulative token usage per session.

Estimates tokens from prompt length (chars / 4 ≈ tokens).
Accumulates across all turns in a session state file.
Injects warnings into Claude's context at thresholds.
Auto-writes handoff at hard limit.

Thresholds:
  50k  tokens → yellow warning
  100k tokens → orange warning + suggest /handoff
  150k tokens → red warning + auto-write handoff + block with message
"""

import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

# Session state file — reset on SessionStart
SESSION_FILE = Path.home() / ".claude" / ".HeadMaster-session-budget.json"

# Thresholds (estimated tokens)
WARN_YELLOW = 50_000
WARN_ORANGE = 100_000
WARN_RED = 150_000

# Chars-per-token estimate (conservative — real ratio is ~3.5-4)
CHARS_PER_TOKEN = 4


def load_session() -> dict:
    if SESSION_FILE.exists():
        try:
            return json.loads(SESSION_FILE.read_text(encoding="utf-8"))
        except Exception:
            pass
    return {"total_tokens": 0, "turn_count": 0, "session_start": datetime.now(timezone.utc).isoformat()}


def save_session(data: dict) -> None:
    SESSION_FILE.parent.mkdir(parents=True, exist_ok=True)
    tmp = SESSION_FILE.with_suffix(".tmp")
    tmp.write_text(json.dumps(data), encoding="utf-8")
    os.replace(str(tmp), str(SESSION_FILE))


def estimate_tokens(text: str) -> int:
    return max(1, len(text) // CHARS_PER_TOKEN)


def format_tokens(n: int) -> str:
    if n >= 1_000_000:
        return f"{n / 1_000_000:.1f}M"
    if n >= 1_000:
        return f"{n / 1_000:.0f}k"
    return str(n)


def write_auto_handoff(total_tokens: int) -> None:
    """Write a minimal session handoff to memory when hard limit hit."""
    try:
        # Find active feature slug from flag file
        flag_file = Path.home() / ".claude" / ".HeadMaster-active"
        slug = "unknown"
        if flag_file.exists():
            try:
                flag = json.loads(flag_file.read_text(encoding="utf-8"))
                slug = flag.get("slug", "unknown")
            except Exception:
                pass

        memory_dir = Path("memory") / "features" / slug
        memory_dir.mkdir(parents=True, exist_ok=True)

        ts = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")
        handoff_path = memory_dir / f"session-{ts}-auto.md"

        content = f"""# Auto-Handoff: Session Budget Exceeded

**Date:** {datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M")} UTC
**Reason:** Session token budget exceeded ({format_tokens(total_tokens)} estimated tokens)
**Feature:** {slug}

## Status
Session was automatically checkpointed. All work is committed to git.

## Next Session
1. Start fresh: `claude --model claude-sonnet-4-6 --name "{slug}"`
2. Run `/navigate {slug}` to detect current phase from artifacts
3. Resume from last gate — no context needed from this session

## What Was In Progress
Check git log for recent commits:
```
git log --oneline -10
```

## Note
This handoff was auto-generated by the token budget hook.
Review `memory/features/{slug}/` for any manually written session notes.
"""
        handoff_path.write_text(content, encoding="utf-8")
    except Exception:
        pass  # Never block the user even if handoff write fails


def main() -> None:
    # Read prompt from hook event (stdin JSON) or argv
    prompt = ""
    try:
        if not sys.stdin.isatty():
            payload = json.loads(sys.stdin.read())
            prompt = payload.get("prompt", "")
    except Exception:
        pass

    if not prompt and len(sys.argv) > 1:
        prompt = sys.argv[1]

    if not prompt:
        sys.exit(0)

    # Estimate tokens for this turn
    turn_tokens = estimate_tokens(prompt)

    # Load and update session state
    session = load_session()
    session["total_tokens"] += turn_tokens
    session["turn_count"] = session.get("turn_count", 0) + 1
    total = session["total_tokens"]
    turns = session["turn_count"]

    save_session(session)

    # Determine warning level
    if total < WARN_YELLOW:
        sys.exit(0)  # No warning needed

    # Build warning message to inject into Claude's context
    bar_filled = min(20, int(20 * total / WARN_RED))
    bar_empty = 20 - bar_filled
    bar = "█" * bar_filled + "░" * bar_empty

    if total >= WARN_RED:
        # Hard limit — auto-write handoff then clear context
        write_auto_handoff(total)
        output = {
            "hookSpecificOutput": {
                "hookEventName": "UserPromptSubmit",
                "additionalContext": f"""
⛔ SESSION BUDGET EXCEEDED — {format_tokens(total)} estimated tokens ({turns} turns)
[{bar}] {format_tokens(total)} / {format_tokens(WARN_RED)}

Auto-handoff written to memory/. All work is in git.
Running /clear to reset context. Session continues — phase re-injected automatically.
"""
            }
        }
    elif total >= WARN_ORANGE:
        output = {
            "hookSpecificOutput": {
                "hookEventName": "UserPromptSubmit",
                "additionalContext": f"""
🟠 SESSION BUDGET WARNING — {format_tokens(total)} estimated tokens ({turns} turns)
[{bar}] {format_tokens(total)} / {format_tokens(WARN_RED)}

Approaching limit. Run /handoff then start a new session soon.
Each message now costs ~{format_tokens(turn_tokens)}+ tokens just for conversation history.
"""
            }
        }
    else:  # WARN_YELLOW
        output = {
            "hookSpecificOutput": {
                "hookEventName": "UserPromptSubmit",
                "additionalContext": f"""
🟡 SESSION BUDGET NOTICE — {format_tokens(total)} estimated tokens ({turns} turns)
[{bar}] {format_tokens(total)} / {format_tokens(WARN_RED)}
"""
            }
        }

    print(json.dumps(output))
    sys.exit(0)


if __name__ == "__main__":
    main()
